### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by moonorblue**
I add some essential import modules and update constants in README, to make the sample code up-to-date with this wrapper :)

### CODE REVIEW

**Comment by jaggedsoft** [comment]
Thank you for your contribution. Looks good to me, though we might need to specify how to get open orders instead of just trade history.

**Comment by jaggedsoft** [comment]
instead if `import Decimal` I had to do this
```py
from decimal import *
```

**Comment by moonorblue** [comment]
> import Decimal

It was a typo in my previous commit, I think` from decimal import Decimal` should work :)

**Comment by moonorblue** [comment]
> Thank you for your contribution. Looks good to me, though we might need to specify how to get open orders instead of just trade history.

I think the original READEME should be clear with the original example `open_orders = client.get_open_orders('tbnb185tqzq3j6y7yep85lncaz9qeectjxqe5054cgn')` ,
And trade history should would be clear in the comment I updated in commit [e0c93](https://github.com/sammchardy/python-binance-chain/pull/13/commits/e0c93d940618ab6de332accb5499ef79e87e00b8) ?

**Pull request merged**
